services:
  - type: web
    name: eld-backend
    env: python
    buildCommand: cd backend-django && pip install -r requirements.txt
    startCommand: cd backend-django && gunicorn eld_app.wsgi --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: MAPBOX_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
