name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd backend-django
        pip install -r requirements.txt
    
    - name: Run migrations
      run: |
        cd backend-django
        python manage.py migrate --noinput
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        DJANGO_SECRET_KEY: test-secret-key
        MAPBOX_TOKEN: test-token
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_SERVICE_ROLE_KEY: test-key
    
    - name: Run tests
      run: |
        cd backend-django
        python manage.py test
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        DJANGO_SECRET_KEY: test-secret-key
        MAPBOX_TOKEN: test-token
        SUPABASE_URL: https://test.supabase.co
        SUPABASE_SERVICE_ROLE_KEY: test-key
